<?php
return $numbers = [
	array( "mask"=> "\+?247[\- ]?\d\d\d\d", "cc"=> "AC", "name_en"=> "Ascension", "desc_en"=> "", "name_ru"=> "Остров Вознесения", "desc_ru"=> "" ),
	array( "mask"=> "\+?376[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "AD", "name_en"=> "Andorra", "desc_en"=> "", "name_ru"=> "Андорра", "desc_ru"=> "" ),
	array( "mask"=> "\+?971[\- ]?5\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AE", "name_en"=> "United Arab Emirates", "desc_en"=> "mobile", "name_ru"=> "Объединенные Арабские Эмираты", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?971[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AE", "name_en"=> "United Arab Emirates", "desc_en"=> "", "name_ru"=> "Объединенные Арабские Эмираты", "desc_ru"=> "" ),
	array( "mask"=> "\+?93[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AF", "name_en"=> "Afghanistan", "desc_en"=> "", "name_ru"=> "Афганистан", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?268[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AG", "name_en"=> "Antigua & Barbuda", "desc_en"=> "", "name_ru"=> "Антигуа и Барбуда", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?264[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AI", "name_en"=> "Anguilla", "desc_en"=> "", "name_ru"=> "Ангилья", "desc_ru"=> "" ),
	array( "mask"=> "\+?355 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "AL", "name_en"=> "Albania", "desc_en"=> "", "name_ru"=> "Албания", "desc_ru"=> "" ),
	array( "mask"=> "\+?374[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "AM", "name_en"=> "Armenia", "desc_en"=> "", "name_ru"=> "Армения", "desc_ru"=> "" ),
	array( "mask"=> "\+?599[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AN", "name_en"=> "Caribbean Netherlands", "desc_en"=> "", "name_ru"=> "Карибские Нидерланды", "desc_ru"=> "" ),
	array( "mask"=> "\+?599[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AN", "name_en"=> "Netherlands Antilles", "desc_en"=> "", "name_ru"=> "Нидерландские Антильские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?599[\- ]?9\d\d\d[\- ]?\d\d\d\d", "cc"=> "AN", "name_en"=> "Netherlands Antilles", "desc_en"=> "Curacao", "name_ru"=> "Нидерландские Антильские острова", "desc_ru"=> "Кюрасао" ),
	array( "mask"=> "\+?244 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "AO", "name_en"=> "Angola", "desc_en"=> "", "name_ru"=> "Ангола", "desc_ru"=> "" ),
	array( "mask"=> "\+?672[\- ]?1\d\d[\- ]?\d\d\d", "cc"=> "AQ", "name_en"=> "Australian bases in Antarctica", "desc_en"=> "", "name_ru"=> "Австралийская антарктическая база", "desc_ru"=> "" ),
	array( "mask"=> "\+?54 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AR", "name_en"=> "Argentina", "desc_en"=> "", "name_ru"=> "Аргентина", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?684[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AS", "name_en"=> "American Samoa", "desc_en"=> "", "name_ru"=> "Американское Самоа", "desc_ru"=> "" ),
	array( "mask"=> "\+?43 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AT", "name_en"=> "Austria", "desc_en"=> "", "name_ru"=> "Австрия", "desc_ru"=> "" ),
	array( "mask"=> "\+?61[\- ]?\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "AU", "name_en"=> "Australia", "desc_en"=> "", "name_ru"=> "Австралия", "desc_ru"=> "" ),
	array( "mask"=> "\+?297[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "AW", "name_en"=> "Aruba", "desc_en"=> "", "name_ru"=> "Аруба", "desc_ru"=> "" ),
	array( "mask"=> "\+?994[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "AZ", "name_en"=> "Azerbaijan", "desc_en"=> "", "name_ru"=> "Азербайджан", "desc_ru"=> "" ),
	array( "mask"=> "\+?387[\- ]?\d\d[\- ]?\d\d\d\d\d", "cc"=> "BA", "name_en"=> "Bosnia and Herzegovina", "desc_en"=> "", "name_ru"=> "Босния и Герцеговина", "desc_ru"=> "" ),
	array( "mask"=> "\+?387[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "BA", "name_en"=> "Bosnia and Herzegovina", "desc_en"=> "", "name_ru"=> "Босния и Герцеговина", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?246[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "BB", "name_en"=> "Barbados", "desc_en"=> "", "name_ru"=> "Барбадос", "desc_ru"=> "" ),
	array( "mask"=> "\+?880[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "BD", "name_en"=> "Bangladesh", "desc_en"=> "", "name_ru"=> "Бангладеш", "desc_ru"=> "" ),
	array( "mask"=> "\+?32 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "BE", "name_en"=> "Belgium", "desc_en"=> "", "name_ru"=> "Бельгия", "desc_ru"=> "" ),
	array( "mask"=> "\+?226[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "BF", "name_en"=> "Burkina Faso", "desc_en"=> "", "name_ru"=> "Буркина Фасо", "desc_ru"=> "" ),
	array( "mask"=> "\+?359 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "BG", "name_en"=> "Bulgaria", "desc_en"=> "", "name_ru"=> "Болгария", "desc_ru"=> "" ),
	array( "mask"=> "\+?973[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "BH", "name_en"=> "Bahrain", "desc_en"=> "", "name_ru"=> "Бахрейн", "desc_ru"=> "" ),
	array( "mask"=> "\+?257[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "BI", "name_en"=> "Burundi", "desc_en"=> "", "name_ru"=> "Бурунди", "desc_ru"=> "" ),
	array( "mask"=> "\+?229[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "BJ", "name_en"=> "Benin", "desc_en"=> "", "name_ru"=> "Бенин", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?441[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "BM", "name_en"=> "Bermuda", "desc_en"=> "", "name_ru"=> "Бермудские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?673[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "BN", "name_en"=> "Brunei Darussalam", "desc_en"=> "", "name_ru"=> "Бруней-Даруссалам", "desc_ru"=> "" ),
	array( "mask"=> "\+?591[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "BO", "name_en"=> "Bolivia", "desc_en"=> "", "name_ru"=> "Боливия", "desc_ru"=> "" ),
	array( "mask"=> "\+?55 ?[( ]?\d\d[) ]? ?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "BR", "name_en"=> "Brazil", "desc_en"=> "", "name_ru"=> "Бразилия", "desc_ru"=> "" ),
	array( "mask"=> "\+?55 ?[( ]?\d\d)7\d\d\d[\- ]?\d\d\d\d", "cc"=> "BR", "name_en"=> "Brazil", "desc_en"=> "mobile", "name_ru"=> "Бразилия", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?55 ?[( ]?\d\d)9\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "BR", "name_en"=> "Brazil", "desc_en"=> "mobile", "name_ru"=> "Бразилия", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?1 ?[( ]?242[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "BS", "name_en"=> "Bahamas", "desc_en"=> "", "name_ru"=> "Багамские Острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?975[\- ]?17[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "BT", "name_en"=> "Bhutan", "desc_en"=> "", "name_ru"=> "Бутан", "desc_ru"=> "" ),
	array( "mask"=> "\+?975[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "BT", "name_en"=> "Bhutan", "desc_en"=> "", "name_ru"=> "Бутан", "desc_ru"=> "" ),
	array( "mask"=> "\+?267[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "BW", "name_en"=> "Botswana", "desc_en"=> "", "name_ru"=> "Ботсвана", "desc_ru"=> "" ),
	array( "mask"=> "\+?375 ?[( ]?\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "BY", "name_en"=> "Belarus", "desc_en"=> "", "name_ru"=> "Беларусь (Белоруссия)", "desc_ru"=> "" ),
	array( "mask"=> "\+?501[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "BZ", "name_en"=> "Belize", "desc_en"=> "", "name_ru"=> "Белиз", "desc_ru"=> "" ),
	array( "mask"=> "\+?243 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "CD", "name_en"=> "Dem. Rep. Congo", "desc_en"=> "", "name_ru"=> "Дем. Респ. Конго (Киншаса)", "desc_ru"=> "" ),
	array( "mask"=> "\+?236[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "CF", "name_en"=> "Central African Republic", "desc_en"=> "", "name_ru"=> "Центральноафриканская Республика", "desc_ru"=> "" ),
	array( "mask"=> "\+?242[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "CG", "name_en"=> "Congo (Brazzaville)", "desc_en"=> "", "name_ru"=> "Конго (Браззавиль)", "desc_ru"=> "" ),
	array( "mask"=> "\+?41[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "CH", "name_en"=> "Switzerland", "desc_en"=> "", "name_ru"=> "Швейцария", "desc_ru"=> "" ),
	array( "mask"=> "\+?225[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "CI", "name_en"=> "Cote d’Ivoire (Ivory Coast)", "desc_en"=> "", "name_ru"=> "Кот-д’Ивуар", "desc_ru"=> "" ),
	array( "mask"=> "\+?682[\- ]?\d\d[\- ]?\d\d\d", "cc"=> "CK", "name_en"=> "Cook Islands", "desc_en"=> "", "name_ru"=> "Острова Кука", "desc_ru"=> "" ),
	array( "mask"=> "\+?56[\- ]?\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "CL", "name_en"=> "Chile", "desc_en"=> "", "name_ru"=> "Чили", "desc_ru"=> "" ),
	array( "mask"=> "\+?237[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "CM", "name_en"=> "Cameroon", "desc_en"=> "", "name_ru"=> "Камерун", "desc_ru"=> "" ),
	array( "mask"=> "\+?86 ?[( ]?\d\d\d[) ]? ?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "CN", "name_en"=> "China (PRC)", "desc_en"=> "", "name_ru"=> "Китайская Н.Р.", "desc_ru"=> "" ),
	array( "mask"=> "\+?86 ?[( ]?\d\d\d[) ]? ?\d\d\d\d[\- ]?\d\d\d", "cc"=> "CN", "name_en"=> "China (PRC)", "desc_en"=> "", "name_ru"=> "Китайская Н.Р.", "desc_ru"=> "" ),
	array( "mask"=> "\+?86[\- ]?\d\d[\- ]?\d\d\d\d\d[\- ]?\d\d\d\d\d", "cc"=> "CN", "name_en"=> "China (PRC)", "desc_en"=> "", "name_ru"=> "Китайская Н.Р.", "desc_ru"=> "" ),
	array( "mask"=> "\+?57 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "CO", "name_en"=> "Colombia", "desc_en"=> "", "name_ru"=> "Колумбия", "desc_ru"=> "" ),
	array( "mask"=> "\+?506[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "CR", "name_en"=> "Costa Rica", "desc_en"=> "", "name_ru"=> "Коста-Рика", "desc_ru"=> "" ),
	array( "mask"=> "\+?53[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "CU", "name_en"=> "Cuba", "desc_en"=> "", "name_ru"=> "Куба", "desc_ru"=> "" ),
	array( "mask"=> "\+?238 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d", "cc"=> "CV", "name_en"=> "Cape Verde", "desc_en"=> "", "name_ru"=> "Кабо-Верде", "desc_ru"=> "" ),
	array( "mask"=> "\+?599[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "CW", "name_en"=> "Curacao", "desc_en"=> "", "name_ru"=> "Кюрасао", "desc_ru"=> "" ),
	array( "mask"=> "\+?357[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "CY", "name_en"=> "Cyprus", "desc_en"=> "", "name_ru"=> "Кипр", "desc_ru"=> "" ),
	array( "mask"=> "\+?420 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "CZ", "name_en"=> "Czech Republic", "desc_en"=> "", "name_ru"=> "Чехия", "desc_ru"=> "" ),
	array( "mask"=> "\+?49 ?[( ]?\d\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DE", "name_en"=> "Germany", "desc_en"=> "", "name_ru"=> "Германия", "desc_ru"=> "" ),
	array( "mask"=> "\+?49 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DE", "name_en"=> "Germany", "desc_en"=> "", "name_ru"=> "Германия", "desc_ru"=> "" ),
	array( "mask"=> "\+?49 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d\d\d", "cc"=> "DE", "name_en"=> "Germany", "desc_en"=> "", "name_ru"=> "Германия", "desc_ru"=> "" ),
	array( "mask"=> "\+?49 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d\d", "cc"=> "DE", "name_en"=> "Germany", "desc_en"=> "", "name_ru"=> "Германия", "desc_ru"=> "" ),
	array( "mask"=> "\+?49 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d", "cc"=> "DE", "name_en"=> "Germany", "desc_en"=> "", "name_ru"=> "Германия", "desc_ru"=> "" ),
	array( "mask"=> "\+?49[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "DE", "name_en"=> "Germany", "desc_en"=> "", "name_ru"=> "Германия", "desc_ru"=> "" ),
	array( "mask"=> "\+?253[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "DJ", "name_en"=> "Djibouti", "desc_en"=> "", "name_ru"=> "Джибути", "desc_ru"=> "" ),
	array( "mask"=> "\+?45[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "DK", "name_en"=> "Denmark", "desc_en"=> "", "name_ru"=> "Дания", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?767[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DM", "name_en"=> "Dominica", "desc_en"=> "", "name_ru"=> "Доминика", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?809[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DO", "name_en"=> "Dominican Republic", "desc_en"=> "", "name_ru"=> "Доминиканская Республика", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?829[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DO", "name_en"=> "Dominican Republic", "desc_en"=> "", "name_ru"=> "Доминиканская Республика", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?849[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DO", "name_en"=> "Dominican Republic", "desc_en"=> "", "name_ru"=> "Доминиканская Республика", "desc_ru"=> "" ),
	array( "mask"=> "\+?213[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "DZ", "name_en"=> "Algeria", "desc_en"=> "", "name_ru"=> "Алжир", "desc_ru"=> "" ),
	array( "mask"=> "\+?593[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "EC", "name_en"=> "Ecuador ", "desc_en"=> "mobile", "name_ru"=> "Эквадор ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?593[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "EC", "name_en"=> "Ecuador", "desc_en"=> "", "name_ru"=> "Эквадор", "desc_ru"=> "" ),
	array( "mask"=> "\+?372[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "EE", "name_en"=> "Estonia ", "desc_en"=> "mobile", "name_ru"=> "Эстония ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?372[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "EE", "name_en"=> "Estonia", "desc_en"=> "", "name_ru"=> "Эстония", "desc_ru"=> "" ),
	array( "mask"=> "\+?20 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "EG", "name_en"=> "Egypt", "desc_en"=> "", "name_ru"=> "Египет", "desc_ru"=> "" ),
	array( "mask"=> "\+?291[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "ER", "name_en"=> "Eritrea", "desc_en"=> "", "name_ru"=> "Эритрея", "desc_ru"=> "" ),
	array( "mask"=> "\+?34 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "ES", "name_en"=> "Spain", "desc_en"=> "", "name_ru"=> "Испания", "desc_ru"=> "" ),
	array( "mask"=> "\+?251[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "ET", "name_en"=> "Ethiopia", "desc_en"=> "", "name_ru"=> "Эфиопия", "desc_ru"=> "" ),
	array( "mask"=> "\+?358 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "FI", "name_en"=> "Finland", "desc_en"=> "", "name_ru"=> "Финляндия", "desc_ru"=> "" ),
	array( "mask"=> "\+?679[\- ]?\d\d[\- ]?\d\d\d\d\d", "cc"=> "FJ", "name_en"=> "Fiji", "desc_en"=> "", "name_ru"=> "Фиджи", "desc_ru"=> "" ),
	array( "mask"=> "\+?500[\- ]?\d\d\d\d\d", "cc"=> "FK", "name_en"=> "Falkland Islands", "desc_en"=> "", "name_ru"=> "Фолклендские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?691[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "FM", "name_en"=> "F.S. Micronesia", "desc_en"=> "", "name_ru"=> "Ф.Ш. Микронезии", "desc_ru"=> "" ),
	array( "mask"=> "\+?298[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "FO", "name_en"=> "Faroe Islands", "desc_en"=> "", "name_ru"=> "Фарерские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?262[\- ]?\d\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "FR", "name_en"=> "Mayotte", "desc_en"=> "", "name_ru"=> "Майотта", "desc_ru"=> "" ),
	array( "mask"=> "\+?33 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "FR", "name_en"=> "France", "desc_en"=> "", "name_ru"=> "Франция", "desc_ru"=> "" ),
	array( "mask"=> "\+?508[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "FR", "name_en"=> "St Pierre & Miquelon", "desc_en"=> "", "name_ru"=> "Сен-Пьер и Микелон", "desc_ru"=> "" ),
	array( "mask"=> "\+?590 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "FR", "name_en"=> "Guadeloupe", "desc_en"=> "", "name_ru"=> "Гваделупа", "desc_ru"=> "" ),
	array( "mask"=> "\+?241[\- ]?\d[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "GA", "name_en"=> "Gabon", "desc_en"=> "", "name_ru"=> "Габон", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?473[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "GD", "name_en"=> "Grenada", "desc_en"=> "", "name_ru"=> "Гренада", "desc_ru"=> "" ),
	array( "mask"=> "\+?995 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "GE", "name_en"=> "Rep. of Georgia", "desc_en"=> "", "name_ru"=> "Грузия", "desc_ru"=> "" ),
	array( "mask"=> "\+?594[\- ]?\d\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "GF", "name_en"=> "Guiana (French)", "desc_en"=> "", "name_ru"=> "Фр. Гвиана", "desc_ru"=> "" ),
	array( "mask"=> "\+?233 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "GH", "name_en"=> "Ghana", "desc_en"=> "", "name_ru"=> "Гана", "desc_ru"=> "" ),
	array( "mask"=> "\+?350[\- ]?\d\d\d[\- ]?\d\d\d\d\d", "cc"=> "GI", "name_en"=> "Gibraltar", "desc_en"=> "", "name_ru"=> "Гибралтар", "desc_ru"=> "" ),
	array( "mask"=> "\+?299[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "GL", "name_en"=> "Greenland", "desc_en"=> "", "name_ru"=> "Гренландия", "desc_ru"=> "" ),
	array( "mask"=> "\+?220 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d", "cc"=> "GM", "name_en"=> "Gambia", "desc_en"=> "", "name_ru"=> "Гамбия", "desc_ru"=> "" ),
	array( "mask"=> "\+?224[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "GN", "name_en"=> "Guinea", "desc_en"=> "", "name_ru"=> "Гвинея", "desc_ru"=> "" ),
	array( "mask"=> "\+?240[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "GQ", "name_en"=> "Equatorial Guinea", "desc_en"=> "", "name_ru"=> "Экваториальная Гвинея", "desc_ru"=> "" ),
	array( "mask"=> "\+?30 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "GR", "name_en"=> "Greece", "desc_en"=> "", "name_ru"=> "Греция", "desc_ru"=> "" ),
	array( "mask"=> "\+?502[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "GT", "name_en"=> "Guatemala", "desc_en"=> "", "name_ru"=> "Гватемала", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?671[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "GU", "name_en"=> "Guam", "desc_en"=> "", "name_ru"=> "Гуам", "desc_ru"=> "" ),
	array( "mask"=> "\+?245[\- ]?\d[\- ]?\d\d\d\d\d\d", "cc"=> "GW", "name_en"=> "Guinea-Bissau", "desc_en"=> "", "name_ru"=> "Гвинея-Бисау", "desc_ru"=> "" ),
	array( "mask"=> "\+?592[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "GY", "name_en"=> "Guyana", "desc_en"=> "", "name_ru"=> "Гайана", "desc_ru"=> "" ),
	array( "mask"=> "\+?852[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "HK", "name_en"=> "Hong Kong", "desc_en"=> "", "name_ru"=> "Гонконг", "desc_ru"=> "" ),
	array( "mask"=> "\+?504[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "HN", "name_en"=> "Honduras", "desc_en"=> "", "name_ru"=> "Гондурас", "desc_ru"=> "" ),
	array( "mask"=> "\+?385[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "HR", "name_en"=> "Croatia", "desc_en"=> "", "name_ru"=> "Хорватия", "desc_ru"=> "" ),
	array( "mask"=> "\+?509[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "HT", "name_en"=> "Haiti", "desc_en"=> "", "name_ru"=> "Гаити", "desc_ru"=> "" ),
	array( "mask"=> "\+?36 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "HU", "name_en"=> "Hungary", "desc_en"=> "", "name_ru"=> "Венгрия", "desc_ru"=> "" ),
	array( "mask"=> "\+?62 ?[( ]?8\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "ID", "name_en"=> "Indonesia ", "desc_en"=> "mobile", "name_ru"=> "Индонезия ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?62[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d", "cc"=> "ID", "name_en"=> "Indonesia", "desc_en"=> "", "name_ru"=> "Индонезия", "desc_ru"=> "" ),
	array( "mask"=> "\+?62[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "ID", "name_en"=> "Indonesia", "desc_en"=> "", "name_ru"=> "Индонезия", "desc_ru"=> "" ),
	array( "mask"=> "\+?62[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "ID", "name_en"=> "Indonesia", "desc_en"=> "", "name_ru"=> "Индонезия", "desc_ru"=> "" ),
	array( "mask"=> "\+?62 ?[( ]?8\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "ID", "name_en"=> "Indonesia ", "desc_en"=> "mobile", "name_ru"=> "Индонезия ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?62 ?[( ]?8\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d\d", "cc"=> "ID", "name_en"=> "Indonesia ", "desc_en"=> "mobile", "name_ru"=> "Индонезия ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?353 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "IE", "name_en"=> "Ireland", "desc_en"=> "", "name_ru"=> "Ирландия", "desc_ru"=> "" ),
	array( "mask"=> "\+?972[\- ]?5\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "IL", "name_en"=> "Israel ", "desc_en"=> "mobile", "name_ru"=> "Израиль ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?972[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "IL", "name_en"=> "Israel", "desc_en"=> "", "name_ru"=> "Израиль", "desc_ru"=> "" ),
	array( "mask"=> "\+?91 ?[( ]?\d\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "IN", "name_en"=> "India", "desc_en"=> "", "name_ru"=> "Индия", "desc_ru"=> "" ),
	array( "mask"=> "\+?246[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "IO", "name_en"=> "Diego Garcia", "desc_en"=> "", "name_ru"=> "Диего-Гарсия", "desc_ru"=> "" ),
	array( "mask"=> "\+?964 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "IQ", "name_en"=> "Iraq", "desc_en"=> "", "name_ru"=> "Ирак", "desc_ru"=> "" ),
	array( "mask"=> "\+?98 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "IR", "name_en"=> "Iran", "desc_en"=> "", "name_ru"=> "Иран", "desc_ru"=> "" ),
	array( "mask"=> "\+?354[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "IS", "name_en"=> "Iceland", "desc_en"=> "", "name_ru"=> "Исландия", "desc_ru"=> "" ),
	array( "mask"=> "\+?39 ?[( ]?\d\d\d[) ]? ?\d\d\d\d[\- ]?\d\d\d", "cc"=> "IT", "name_en"=> "Italy", "desc_en"=> "", "name_ru"=> "Италия", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?876[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "JM", "name_en"=> "Jamaica", "desc_en"=> "", "name_ru"=> "Ямайка", "desc_ru"=> "" ),
	array( "mask"=> "\+?962[\- ]?\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "JO", "name_en"=> "Jordan", "desc_en"=> "", "name_ru"=> "Иордания", "desc_ru"=> "" ),
	array( "mask"=> "\+?81[\- ]?\d\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "JP", "name_en"=> "Japan ", "desc_en"=> "mobile", "name_ru"=> "Япония ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?81 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "JP", "name_en"=> "Japan", "desc_en"=> "", "name_ru"=> "Япония", "desc_ru"=> "" ),
	array( "mask"=> "\+?254[\- ]?\d\d\d[\- ]?\d\d\d\d\d\d", "cc"=> "KE", "name_en"=> "Kenya", "desc_en"=> "", "name_ru"=> "Кения", "desc_ru"=> "" ),
	array( "mask"=> "\+?996 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "KG", "name_en"=> "Kyrgyzstan", "desc_en"=> "", "name_ru"=> "Киргизия", "desc_ru"=> "" ),
	array( "mask"=> "\+?855[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "KH", "name_en"=> "Cambodia", "desc_en"=> "", "name_ru"=> "Камбоджа", "desc_ru"=> "" ),
	array( "mask"=> "\+?686[\- ]?\d\d[\- ]?\d\d\d", "cc"=> "KI", "name_en"=> "Kiribati", "desc_en"=> "", "name_ru"=> "Кирибати", "desc_ru"=> "" ),
	array( "mask"=> "\+?269[\- ]?\d\d[\- ]?\d\d\d\d\d", "cc"=> "KM", "name_en"=> "Comoros", "desc_en"=> "", "name_ru"=> "Коморы", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?869[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "KN", "name_en"=> "Saint Kitts & Nevis", "desc_en"=> "", "name_ru"=> "Сент-Китс и Невис", "desc_ru"=> "" ),
	array( "mask"=> "\+?850[\- ]?191[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "KP", "name_en"=> "DPR Korea (North) ", "desc_en"=> "mobile", "name_ru"=> "Корейская НДР ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?850[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "KP", "name_en"=> "DPR Korea (North)", "desc_en"=> "", "name_ru"=> "Корейская НДР", "desc_ru"=> "" ),
	array( "mask"=> "\+?850[\- ]?\d\d\d[\- ]?\d\d\d\d[\- ]?\d\d\d", "cc"=> "KP", "name_en"=> "DPR Korea (North)", "desc_en"=> "", "name_ru"=> "Корейская НДР", "desc_ru"=> "" ),
	array( "mask"=> "\+?850[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "KP", "name_en"=> "DPR Korea (North)", "desc_en"=> "", "name_ru"=> "Корейская НДР", "desc_ru"=> "" ),
	array( "mask"=> "\+?850[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "KP", "name_en"=> "DPR Korea (North)", "desc_en"=> "", "name_ru"=> "Корейская НДР", "desc_ru"=> "" ),
	array( "mask"=> "\+?850[\- ]?\d\d\d\d[\- ]?\d\d\d\d\d\d\d\d\d\d\d\d\d", "cc"=> "KP", "name_en"=> "DPR Korea (North)", "desc_en"=> "", "name_ru"=> "Корейская НДР", "desc_ru"=> "" ),
	array( "mask"=> "\+?82[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "KR", "name_en"=> "Korea (South)", "desc_en"=> "", "name_ru"=> "Респ. Корея", "desc_ru"=> "" ),
	array( "mask"=> "\+?965[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "KW", "name_en"=> "Kuwait", "desc_en"=> "", "name_ru"=> "Кувейт", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?345[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "KY", "name_en"=> "Cayman Islands", "desc_en"=> "", "name_ru"=> "Каймановы острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?7 ?[( ]?6\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "KZ", "name_en"=> "Kazakhstan", "desc_en"=> "", "name_ru"=> "Казахстан", "desc_ru"=> "" ),
	array( "mask"=> "\+?7 ?[( ]?7\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "KZ", "name_en"=> "Kazakhstan", "desc_en"=> "", "name_ru"=> "Казахстан", "desc_ru"=> "" ),
	array( "mask"=> "\+?856 ?[( ]?20\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "LA", "name_en"=> "Laos ", "desc_en"=> "mobile", "name_ru"=> "Лаос ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?856[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "LA", "name_en"=> "Laos", "desc_en"=> "", "name_ru"=> "Лаос", "desc_ru"=> "" ),
	array( "mask"=> "\+?961[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "LB", "name_en"=> "Lebanon ", "desc_en"=> "mobile", "name_ru"=> "Ливан ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?961[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "LB", "name_en"=> "Lebanon", "desc_en"=> "", "name_ru"=> "Ливан", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?758[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "LC", "name_en"=> "Saint Lucia", "desc_en"=> "", "name_ru"=> "Сент-Люсия", "desc_ru"=> "" ),
	array( "mask"=> "\+?423 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "LI", "name_en"=> "Liechtenstein", "desc_en"=> "", "name_ru"=> "Лихтенштейн", "desc_ru"=> "" ),
	array( "mask"=> "\+?94[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "LK", "name_en"=> "Sri Lanka", "desc_en"=> "", "name_ru"=> "Шри-Ланка", "desc_ru"=> "" ),
	array( "mask"=> "\+?231[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "LR", "name_en"=> "Liberia", "desc_en"=> "", "name_ru"=> "Либерия", "desc_ru"=> "" ),
	array( "mask"=> "\+?266[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "LS", "name_en"=> "Lesotho", "desc_en"=> "", "name_ru"=> "Лесото", "desc_ru"=> "" ),
	array( "mask"=> "\+?370 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d\d", "cc"=> "LT", "name_en"=> "Lithuania", "desc_en"=> "", "name_ru"=> "Литва", "desc_ru"=> "" ),
	array( "mask"=> "\+?352 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "LU", "name_en"=> "Luxembourg", "desc_en"=> "", "name_ru"=> "Люксембург", "desc_ru"=> "" ),
	array( "mask"=> "\+?371[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "LV", "name_en"=> "Latvia", "desc_en"=> "", "name_ru"=> "Латвия", "desc_ru"=> "" ),
	array( "mask"=> "\+?218[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "LY", "name_en"=> "Libya", "desc_en"=> "", "name_ru"=> "Ливия", "desc_ru"=> "" ),
	array( "mask"=> "\+?218[\- ]?21[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "LY", "name_en"=> "Libya", "desc_en"=> "Tripoli", "name_ru"=> "Ливия", "desc_ru"=> "Триполи" ),
	array( "mask"=> "\+?212[\- ]?\d\d[\- ]?\d\d\d\d[\- ]?\d\d\d", "cc"=> "MA", "name_en"=> "Morocco", "desc_en"=> "", "name_ru"=> "Марокко", "desc_ru"=> "" ),
	array( "mask"=> "\+?377 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "MC", "name_en"=> "Monaco", "desc_en"=> "", "name_ru"=> "Монако", "desc_ru"=> "" ),
	array( "mask"=> "\+?377[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MC", "name_en"=> "Monaco", "desc_en"=> "", "name_ru"=> "Монако", "desc_ru"=> "" ),
	array( "mask"=> "\+?373[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "MD", "name_en"=> "Moldova", "desc_en"=> "", "name_ru"=> "Молдова", "desc_ru"=> "" ),
	array( "mask"=> "\+?382[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "ME", "name_en"=> "Montenegro", "desc_en"=> "", "name_ru"=> "Черногория", "desc_ru"=> "" ),
	array( "mask"=> "\+?261[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d\d", "cc"=> "MG", "name_en"=> "Madagascar", "desc_en"=> "", "name_ru"=> "Мадагаскар", "desc_ru"=> "" ),
	array( "mask"=> "\+?692[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MH", "name_en"=> "Marshall Islands", "desc_en"=> "", "name_ru"=> "Маршалловы Острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?389[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MK", "name_en"=> "Republic of Macedonia", "desc_en"=> "", "name_ru"=> "Респ. Македония", "desc_ru"=> "" ),
	array( "mask"=> "\+?223[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "ML", "name_en"=> "Mali", "desc_en"=> "", "name_ru"=> "Мали", "desc_ru"=> "" ),
	array( "mask"=> "\+?95[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MM", "name_en"=> "Burma (Myanmar)", "desc_en"=> "", "name_ru"=> "Бирма (Мьянма)", "desc_ru"=> "" ),
	array( "mask"=> "\+?95[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MM", "name_en"=> "Burma (Myanmar)", "desc_en"=> "", "name_ru"=> "Бирма (Мьянма)", "desc_ru"=> "" ),
	array( "mask"=> "\+?95[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MM", "name_en"=> "Burma (Myanmar)", "desc_en"=> "", "name_ru"=> "Бирма (Мьянма)", "desc_ru"=> "" ),
	array( "mask"=> "\+?976[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "MN", "name_en"=> "Mongolia", "desc_en"=> "", "name_ru"=> "Монголия", "desc_ru"=> "" ),
	array( "mask"=> "\+?853[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "MO", "name_en"=> "Macau", "desc_en"=> "", "name_ru"=> "Макао", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?670[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MP", "name_en"=> "Northern Mariana Islands", "desc_en"=> "", "name_ru"=> "Северные Марианские острова Сайпан", "desc_ru"=> "" ),
	array( "mask"=> "\+?596 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "MQ", "name_en"=> "Martinique", "desc_en"=> "", "name_ru"=> "Мартиника", "desc_ru"=> "" ),
	array( "mask"=> "\+?222[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "MR", "name_en"=> "Mauritania", "desc_en"=> "", "name_ru"=> "Мавритания", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?664[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MS", "name_en"=> "Montserrat", "desc_en"=> "", "name_ru"=> "Монтсеррат", "desc_ru"=> "" ),
	array( "mask"=> "\+?356[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "MT", "name_en"=> "Malta", "desc_en"=> "", "name_ru"=> "Мальта", "desc_ru"=> "" ),
	array( "mask"=> "\+?230[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MU", "name_en"=> "Mauritius", "desc_en"=> "", "name_ru"=> "Маврикий", "desc_ru"=> "" ),
	array( "mask"=> "\+?960[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MV", "name_en"=> "Maldives", "desc_en"=> "", "name_ru"=> "Мальдивские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?265[\- ]?1[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MW", "name_en"=> "Malawi", "desc_en"=> "Telecom Ltd", "name_ru"=> "Малави", "desc_ru"=> "Telecom Ltd" ),
	array( "mask"=> "\+?265[\- ]?\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "MW", "name_en"=> "Malawi", "desc_en"=> "", "name_ru"=> "Малави", "desc_ru"=> "" ),
	array( "mask"=> "\+?52 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MX", "name_en"=> "Mexico", "desc_en"=> "", "name_ru"=> "Мексика", "desc_ru"=> "" ),
	array( "mask"=> "\+?52[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "MX", "name_en"=> "Mexico", "desc_en"=> "", "name_ru"=> "Мексика", "desc_ru"=> "" ),
	array( "mask"=> "\+?60[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "MY", "name_en"=> "Malaysia ", "desc_en"=> "mobile", "name_ru"=> "Малайзия ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?60 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "MY", "name_en"=> "Malaysia", "desc_en"=> "", "name_ru"=> "Малайзия", "desc_ru"=> "" ),
	array( "mask"=> "\+?60[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MY", "name_en"=> "Malaysia", "desc_en"=> "", "name_ru"=> "Малайзия", "desc_ru"=> "" ),
	array( "mask"=> "\+?60[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MY", "name_en"=> "Malaysia", "desc_en"=> "", "name_ru"=> "Малайзия", "desc_ru"=> "" ),
	array( "mask"=> "\+?258[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "MZ", "name_en"=> "Mozambique", "desc_en"=> "", "name_ru"=> "Мозамбик", "desc_ru"=> "" ),
	array( "mask"=> "\+?264[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "NA", "name_en"=> "Namibia", "desc_en"=> "", "name_ru"=> "Намибия", "desc_ru"=> "" ),
	array( "mask"=> "\+?687[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "NC", "name_en"=> "New Caledonia", "desc_en"=> "", "name_ru"=> "Новая Каледония", "desc_ru"=> "" ),
	array( "mask"=> "\+?227[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "NE", "name_en"=> "Niger", "desc_en"=> "", "name_ru"=> "Нигер", "desc_ru"=> "" ),
	array( "mask"=> "\+?672[\- ]?3\d\d[\- ]?\d\d\d", "cc"=> "NF", "name_en"=> "Norfolk Island", "desc_en"=> "", "name_ru"=> "Норфолк (остров)", "desc_ru"=> "" ),
	array( "mask"=> "\+?234 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "NG", "name_en"=> "Nigeria", "desc_en"=> "", "name_ru"=> "Нигерия", "desc_ru"=> "" ),
	array( "mask"=> "\+?234[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "NG", "name_en"=> "Nigeria", "desc_en"=> "", "name_ru"=> "Нигерия", "desc_ru"=> "" ),
	array( "mask"=> "\+?234[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d", "cc"=> "NG", "name_en"=> "Nigeria", "desc_en"=> "", "name_ru"=> "Нигерия", "desc_ru"=> "" ),
	array( "mask"=> "\+?234 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "NG", "name_en"=> "Nigeria ", "desc_en"=> "mobile", "name_ru"=> "Нигерия ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?505[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "NI", "name_en"=> "Nicaragua", "desc_en"=> "", "name_ru"=> "Никарагуа", "desc_ru"=> "" ),
	array( "mask"=> "\+?31[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "NL", "name_en"=> "Netherlands", "desc_en"=> "", "name_ru"=> "Нидерланды", "desc_ru"=> "" ),
	array( "mask"=> "\+?47 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d\d", "cc"=> "NO", "name_en"=> "Norway", "desc_en"=> "", "name_ru"=> "Норвегия", "desc_ru"=> "" ),
	array( "mask"=> "\+?977[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "NP", "name_en"=> "Nepal", "desc_en"=> "", "name_ru"=> "Непал", "desc_ru"=> "" ),
	array( "mask"=> "\+?674[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "NR", "name_en"=> "Nauru", "desc_en"=> "", "name_ru"=> "Науру", "desc_ru"=> "" ),
	array( "mask"=> "\+?683[\- ]?\d\d\d\d", "cc"=> "NU", "name_en"=> "Niue", "desc_en"=> "", "name_ru"=> "Ниуэ", "desc_ru"=> "" ),
	array( "mask"=> "\+?64 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "NZ", "name_en"=> "New Zealand", "desc_en"=> "", "name_ru"=> "Новая Зеландия", "desc_ru"=> "" ),
	array( "mask"=> "\+?64[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "NZ", "name_en"=> "New Zealand", "desc_en"=> "", "name_ru"=> "Новая Зеландия", "desc_ru"=> "" ),
	array( "mask"=> "\+?64 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "NZ", "name_en"=> "New Zealand", "desc_en"=> "", "name_ru"=> "Новая Зеландия", "desc_ru"=> "" ),
	array( "mask"=> "\+?968[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "OM", "name_en"=> "Oman", "desc_en"=> "", "name_ru"=> "Оман", "desc_ru"=> "" ),
	array( "mask"=> "\+?507[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "PA", "name_en"=> "Panama", "desc_en"=> "", "name_ru"=> "Панама", "desc_ru"=> "" ),
	array( "mask"=> "\+?51 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "PE", "name_en"=> "Peru", "desc_en"=> "", "name_ru"=> "Перу", "desc_ru"=> "" ),
	array( "mask"=> "\+?689[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "PF", "name_en"=> "French Polynesia", "desc_en"=> "", "name_ru"=> "Французская Полинезия (Таити)", "desc_ru"=> "" ),
	array( "mask"=> "\+?675 ?[( ]?\d\d\d[) ]? ?\d\d[\- ]?\d\d\d", "cc"=> "PG", "name_en"=> "Papua New Guinea", "desc_en"=> "", "name_ru"=> "Папуа-Новая Гвинея", "desc_ru"=> "" ),
	array( "mask"=> "\+?63 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "PH", "name_en"=> "Philippines", "desc_en"=> "", "name_ru"=> "Филиппины", "desc_ru"=> "" ),
	array( "mask"=> "\+?92 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "PK", "name_en"=> "Pakistan", "desc_en"=> "", "name_ru"=> "Пакистан", "desc_ru"=> "" ),
	array( "mask"=> "\+?48 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "PL", "name_en"=> "Poland", "desc_en"=> "", "name_ru"=> "Польша", "desc_ru"=> "" ),
	array( "mask"=> "\+?970[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "PS", "name_en"=> "Palestine", "desc_en"=> "", "name_ru"=> "Палестина", "desc_ru"=> "" ),
	array( "mask"=> "\+?351[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "PT", "name_en"=> "Portugal", "desc_en"=> "", "name_ru"=> "Португалия", "desc_ru"=> "" ),
	array( "mask"=> "\+?680[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "PW", "name_en"=> "Palau", "desc_en"=> "", "name_ru"=> "Палау", "desc_ru"=> "" ),
	array( "mask"=> "\+?595 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "PY", "name_en"=> "Paraguay", "desc_en"=> "", "name_ru"=> "Парагвай", "desc_ru"=> "" ),
	array( "mask"=> "\+?974[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "QA", "name_en"=> "Qatar", "desc_en"=> "", "name_ru"=> "Катар", "desc_ru"=> "" ),
	array( "mask"=> "\+?262[\- ]?\d\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "RE", "name_en"=> "Reunion", "desc_en"=> "", "name_ru"=> "Реюньон", "desc_ru"=> "" ),
	array( "mask"=> "\+?40[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "RO", "name_en"=> "Romania", "desc_en"=> "", "name_ru"=> "Румыния", "desc_ru"=> "" ),
	array( "mask"=> "\+?381[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "RS", "name_en"=> "Serbia", "desc_en"=> "", "name_ru"=> "Сербия", "desc_ru"=> "" ),
	array( "mask"=> "\+?7 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "RU", "name_en"=> "Russia", "desc_en"=> "", "name_ru"=> "Россия", "desc_ru"=> "" ),
	array( "mask"=> "\+?250 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "RW", "name_en"=> "Rwanda", "desc_en"=> "", "name_ru"=> "Руанда", "desc_ru"=> "" ),
	array( "mask"=> "\+?966[\- ]?5[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "SA", "name_en"=> "Saudi Arabia ", "desc_en"=> "mobile", "name_ru"=> "Саудовская Аравия ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?966[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SA", "name_en"=> "Saudi Arabia", "desc_en"=> "", "name_ru"=> "Саудовская Аравия", "desc_ru"=> "" ),
	array( "mask"=> "\+?677[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SB", "name_en"=> "Solomon Islands ", "desc_en"=> "mobile", "name_ru"=> "Соломоновы Острова ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?677[\- ]?\d\d\d\d\d", "cc"=> "SB", "name_en"=> "Solomon Islands", "desc_en"=> "", "name_ru"=> "Соломоновы Острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?248[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "SC", "name_en"=> "Seychelles", "desc_en"=> "", "name_ru"=> "Сейшелы", "desc_ru"=> "" ),
	array( "mask"=> "\+?249[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SD", "name_en"=> "Sudan", "desc_en"=> "", "name_ru"=> "Судан", "desc_ru"=> "" ),
	array( "mask"=> "\+?46[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SE", "name_en"=> "Sweden", "desc_en"=> "", "name_ru"=> "Швеция", "desc_ru"=> "" ),
	array( "mask"=> "\+?65[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "SG", "name_en"=> "Singapore", "desc_en"=> "", "name_ru"=> "Сингапур", "desc_ru"=> "" ),
	array( "mask"=> "\+?290[\- ]?\d\d\d\d", "cc"=> "SH", "name_en"=> "Saint Helena", "desc_en"=> "", "name_ru"=> "Остров Святой Елены", "desc_ru"=> "" ),
	array( "mask"=> "\+?290[\- ]?\d\d\d\d", "cc"=> "SH", "name_en"=> "Tristan da Cunha", "desc_en"=> "", "name_ru"=> "Тристан-да-Кунья", "desc_ru"=> "" ),
	array( "mask"=> "\+?386[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "SI", "name_en"=> "Slovenia", "desc_en"=> "", "name_ru"=> "Словения", "desc_ru"=> "" ),
	array( "mask"=> "\+?421 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "SK", "name_en"=> "Slovakia", "desc_en"=> "", "name_ru"=> "Словакия", "desc_ru"=> "" ),
	array( "mask"=> "\+?232[\- ]?\d\d[\- ]?\d\d\d\d\d\d", "cc"=> "SL", "name_en"=> "Sierra Leone", "desc_en"=> "", "name_ru"=> "Сьерра-Леоне", "desc_ru"=> "" ),
	array( "mask"=> "\+?378[\- ]?\d\d\d\d[\- ]?\d\d\d\d\d\d", "cc"=> "SM", "name_en"=> "San Marino", "desc_en"=> "", "name_ru"=> "Сан-Марино", "desc_ru"=> "" ),
	array( "mask"=> "\+?221[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SN", "name_en"=> "Senegal", "desc_en"=> "", "name_ru"=> "Сенегал", "desc_ru"=> "" ),
	array( "mask"=> "\+?252[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "SO", "name_en"=> "Somalia", "desc_en"=> "", "name_ru"=> "Сомали", "desc_ru"=> "" ),
	array( "mask"=> "\+?252[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "SO", "name_en"=> "Somalia", "desc_en"=> "", "name_ru"=> "Сомали", "desc_ru"=> "" ),
	array( "mask"=> "\+?252[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "SO", "name_en"=> "Somalia ", "desc_en"=> "mobile", "name_ru"=> "Сомали ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?597[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SR", "name_en"=> "Suriname ", "desc_en"=> "mobile", "name_ru"=> "Суринам ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?597[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "SR", "name_en"=> "Suriname", "desc_en"=> "", "name_ru"=> "Суринам", "desc_ru"=> "" ),
	array( "mask"=> "\+?211[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SS", "name_en"=> "South Sudan", "desc_en"=> "", "name_ru"=> "Южный Судан", "desc_ru"=> "" ),
	array( "mask"=> "\+?239[\- ]?\d\d[\- ]?\d\d\d\d\d", "cc"=> "ST", "name_en"=> "Sao Tome and Principe", "desc_en"=> "", "name_ru"=> "Сан-Томе и Принсипи", "desc_ru"=> "" ),
	array( "mask"=> "\+?503[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "SV", "name_en"=> "El Salvador", "desc_en"=> "", "name_ru"=> "Сальвадор", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?721[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "SX", "name_en"=> "Sint Maarten", "desc_en"=> "", "name_ru"=> "Синт-Маартен", "desc_ru"=> "" ),
	array( "mask"=> "\+?963[\- ]?\d\d[\- ]?\d\d\d\d[\- ]?\d\d\d", "cc"=> "SY", "name_en"=> "Syrian Arab Republic", "desc_en"=> "", "name_ru"=> "Сирийская арабская республика", "desc_ru"=> "" ),
	array( "mask"=> "\+?268[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "SZ", "name_en"=> "Swaziland", "desc_en"=> "", "name_ru"=> "Свазиленд", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?649[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TC", "name_en"=> "Turks & Caicos", "desc_en"=> "", "name_ru"=> "Тёркс и Кайкос", "desc_ru"=> "" ),
	array( "mask"=> "\+?235[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "TD", "name_en"=> "Chad", "desc_en"=> "", "name_ru"=> "Чад", "desc_ru"=> "" ),
	array( "mask"=> "\+?228[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "TG", "name_en"=> "Togo", "desc_en"=> "", "name_ru"=> "Того", "desc_ru"=> "" ),
	array( "mask"=> "\+?66[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TH", "name_en"=> "Thailand ", "desc_en"=> "mobile", "name_ru"=> "Таиланд ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?66[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "TH", "name_en"=> "Thailand", "desc_en"=> "", "name_ru"=> "Таиланд", "desc_ru"=> "" ),
	array( "mask"=> "\+?992[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TJ", "name_en"=> "Tajikistan", "desc_en"=> "", "name_ru"=> "Таджикистан", "desc_ru"=> "" ),
	array( "mask"=> "\+?690[\- ]?\d\d\d\d", "cc"=> "TK", "name_en"=> "Tokelau", "desc_en"=> "", "name_ru"=> "Токелау", "desc_ru"=> "" ),
	array( "mask"=> "\+?670[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TL", "name_en"=> "East Timor", "desc_en"=> "", "name_ru"=> "Восточный Тимор", "desc_ru"=> "" ),
	array( "mask"=> "\+?670[\- ]?77\d[\- ]?\d\d\d\d\d", "cc"=> "TL", "name_en"=> "East Timor", "desc_en"=> "Timor Telecom", "name_ru"=> "Восточный Тимор", "desc_ru"=> "Timor Telecom" ),
	array( "mask"=> "\+?670[\- ]?78\d[\- ]?\d\d\d\d\d", "cc"=> "TL", "name_en"=> "East Timor", "desc_en"=> "Timor Telecom", "name_ru"=> "Восточный Тимор", "desc_ru"=> "Timor Telecom" ),
	array( "mask"=> "\+?993[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TM", "name_en"=> "Turkmenistan", "desc_en"=> "", "name_ru"=> "Туркменистан", "desc_ru"=> "" ),
	array( "mask"=> "\+?216[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "TN", "name_en"=> "Tunisia", "desc_en"=> "", "name_ru"=> "Тунис", "desc_ru"=> "" ),
	array( "mask"=> "\+?676[\- ]?\d\d\d\d\d", "cc"=> "TO", "name_en"=> "Tonga", "desc_en"=> "", "name_ru"=> "Тонга", "desc_ru"=> "" ),
	array( "mask"=> "\+?90 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TR", "name_en"=> "Turkey", "desc_en"=> "", "name_ru"=> "Турция", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?868[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TT", "name_en"=> "Trinidad & Tobago", "desc_en"=> "", "name_ru"=> "Тринидад и Тобаго", "desc_ru"=> "" ),
	array( "mask"=> "\+?688[\- ]?90\d\d\d\d", "cc"=> "TV", "name_en"=> "Tuvalu ", "desc_en"=> "mobile", "name_ru"=> "Тувалу ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?688[\- ]?2\d\d\d\d", "cc"=> "TV", "name_en"=> "Tuvalu", "desc_en"=> "", "name_ru"=> "Тувалу", "desc_ru"=> "" ),
	array( "mask"=> "\+?886[\- ]?\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "TW", "name_en"=> "Taiwan", "desc_en"=> "", "name_ru"=> "Тайвань", "desc_ru"=> "" ),
	array( "mask"=> "\+?886[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "TW", "name_en"=> "Taiwan", "desc_en"=> "", "name_ru"=> "Тайвань", "desc_ru"=> "" ),
	array( "mask"=> "\+?255[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "TZ", "name_en"=> "Tanzania", "desc_en"=> "", "name_ru"=> "Танзания", "desc_ru"=> "" ),
	array( "mask"=> "\+?380 ?[( ]?\d\d[) ]? ?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "UA", "name_en"=> "Ukraine", "desc_en"=> "", "name_ru"=> "Украина", "desc_ru"=> "" ),
	array( "mask"=> "\+?256 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d", "cc"=> "UG", "name_en"=> "Uganda", "desc_en"=> "", "name_ru"=> "Уганда", "desc_ru"=> "" ),
	array( "mask"=> "\+?44[\- ]?\d\d[\- ]?\d\d\d\d[\- ]?\d\d\d\d", "cc"=> "UK", "name_en"=> "United Kingdom", "desc_en"=> "", "name_ru"=> "Великобритания", "desc_ru"=> "" ),
	array( "mask"=> "\+?598[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d[\- ]?\d\d", "cc"=> "UY", "name_en"=> "Uruguay", "desc_en"=> "", "name_ru"=> "Уругвай", "desc_ru"=> "" ),
	array( "mask"=> "\+?998[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "UZ", "name_en"=> "Uzbekistan", "desc_en"=> "", "name_ru"=> "Узбекистан", "desc_ru"=> "" ),
	array( "mask"=> "\+?39[\- ]?6[\- ]?698[\- ]?\d\d\d\d\d", "cc"=> "VA", "name_en"=> "Vatican City", "desc_en"=> "", "name_ru"=> "Ватикан", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?784[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "VC", "name_en"=> "Saint Vincent & the Grenadines", "desc_en"=> "", "name_ru"=> "Сент-Винсент и Гренадины", "desc_ru"=> "" ),
	array( "mask"=> "\+?58 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "VE", "name_en"=> "Venezuela", "desc_en"=> "", "name_ru"=> "Венесуэла", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?284[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "VG", "name_en"=> "British Virgin Islands", "desc_en"=> "", "name_ru"=> "Британские Виргинские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?340[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> "VI", "name_en"=> "US Virgin Islands", "desc_en"=> "", "name_ru"=> "Американские Виргинские острова", "desc_ru"=> "" ),
	array( "mask"=> "\+?84[\- ]?\d\d[\- ]?\d\d\d\d[\- ]?\d\d\d", "cc"=> "VN", "name_en"=> "Vietnam", "desc_en"=> "", "name_ru"=> "Вьетнам", "desc_ru"=> "" ),
	array( "mask"=> "\+?84 ?[( ]?\d\d\d[) ]? ?\d\d\d\d[\- ]?\d\d\d", "cc"=> "VN", "name_en"=> "Vietnam", "desc_en"=> "", "name_ru"=> "Вьетнам", "desc_ru"=> "" ),
	array( "mask"=> "\+?678[\- ]?\d\d[\- ]?\d\d\d\d\d", "cc"=> "VU", "name_en"=> "Vanuatu ", "desc_en"=> "mobile", "name_ru"=> "Вануату ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?678[\- ]?\d\d\d\d\d", "cc"=> "VU", "name_en"=> "Vanuatu", "desc_en"=> "", "name_ru"=> "Вануату", "desc_ru"=> "" ),
	array( "mask"=> "\+?681[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "WF", "name_en"=> "Wallis and Futuna", "desc_en"=> "", "name_ru"=> "Уоллис и Футуна", "desc_ru"=> "" ),
	array( "mask"=> "\+?685[\- ]?\d\d[\- ]?\d\d\d\d", "cc"=> "WS", "name_en"=> "Samoa", "desc_en"=> "", "name_ru"=> "Самоа", "desc_ru"=> "" ),
	array( "mask"=> "\+?967[\- ]?\d\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "YE", "name_en"=> "Yemen ", "desc_en"=> "mobile", "name_ru"=> "Йемен ", "desc_ru"=> "мобильные" ),
	array( "mask"=> "\+?967[\- ]?\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "YE", "name_en"=> "Yemen", "desc_en"=> "", "name_ru"=> "Йемен", "desc_ru"=> "" ),
	array( "mask"=> "\+?967[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d", "cc"=> "YE", "name_en"=> "Yemen", "desc_en"=> "", "name_ru"=> "Йемен", "desc_ru"=> "" ),
	array( "mask"=> "\+?27[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "ZA", "name_en"=> "South Africa", "desc_en"=> "", "name_ru"=> "Южно-Африканская Респ.", "desc_ru"=> "" ),
	array( "mask"=> "\+?260[\- ]?\d\d[\- ]?\d\d\d[\- ]?\d\d\d\d", "cc"=> "ZM", "name_en"=> "Zambia", "desc_en"=> "", "name_ru"=> "Замбия", "desc_ru"=> "" ),
	array( "mask"=> "\+?263[\- ]?\d[\- ]?\d\d\d\d\d\d", "cc"=> "ZW", "name_en"=> "Zimbabwe", "desc_en"=> "", "name_ru"=> "Зимбабве", "desc_ru"=> "" ),
	array( "mask"=> "\+?1 ?[( ]?\d\d\d[) ]? ?\d\d\d[\- ]?\d\d\d\d", "cc"=> ["US", "CA"], "name_en"=> "USA and Canada", "desc_en"=> "", "name_ru"=> "США и Канада", "desc_ru"=> "" )
]
?>